version: "3"

services:
  postgres:
    ports:
      - 127.0.0.1:5432:5432
    image: postgres:14.2-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: FastAPI
      POSTGRES_PASSWORD: postgres
    networks:
      back:

volumes:
  postgres-data:

networks:
  back:
    driver: bridge
